### ISSUE TITLE
5v does not work

### ISSUE THREAD

**Issue by Miskler** [AlexiyOrlov/trajectory-preview#2]
Forge
1.19.4
mod v5.0.1

It just doesn't work, no errors, no crashes, just the trajectory is not displayed anywhere

**Comment by Miskler** [comment]
```
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2023-06-11 05:01:00
Description: Unexpected error

java.lang.NoSuchMethodError: 'net.minecraft.world.entity.Entity net.minecraft.world.entity.projectile.AbstractArrow.m_37282_()'
	at dev.buildtool.traj.preview.BowArrowPreview.simulateShot(BowArrowPreview.java:105) ~[trajectorypreview-5.0.1-1.19.3.jar%23176!/:5.0.1-1.19.3] {re:classloading}
	at dev.buildtool.traj.preview.BowArrowPreview.simulateShot(BowArrowPreview.java:31) ~[trajectorypreview-5.0.1-1.19.3.jar%23176!/:5.0.1-1.19.3] {re:classloading}
	at dev.buildtool.traj.preview.Events.drawTrajectory(Events.java:61) ~[trajectorypreview-5.0.1-1.19.3.jar%23176!/:5.0.1-1.19.3] {re:classloading}
	at dev.buildtool.traj.preview.__Events_drawTrajectory_Post.invoke(.dynamic) ~[trajectorypreview-5.0.1-1.19.3.jar%23176!/:5.0.1-1.19.3] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.client.gui.overlay.ForgeGui.post(ForgeGui.java:660) ~[forge-1.19.4-45.0.42-universal.jar%23183!/:?] {re:classloading}
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:139) ~[forge-1.19.4-45.0.42-universal.jar%23183!/:?] {re:classloading}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%2399!/:?] {}
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:133) ~[forge-1.19.4-45.0.42-universal.jar%23183!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1309) ~[client-1.19.4-20230314.122934-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:jade.mixins.json:GameRendererMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1160) ~[client-1.19.4-20230314.122934-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:731) ~[client-1.19.4-20230314.122934-srg.jar%23178!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:iceberg.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[ForgeOptiFine%201.19.4.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.42.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
```
And sometimes it crashes

**Comment by Miskler** [comment]
Now I'm using version 4.5.0, so far I haven't noticed any problems

**Comment by AlexiyOrlov** [comment]
I uploaded next version, maybe it will work
